# Compilador
CXX = g++

# Compilación de cliente
cliente: cliente.cpp
	$(CXX) -o cliente cliente.cpp

# Limpiar ejecutables
clean:
	rm -f cliente

# Ejecutar el cliente
./cliente <direccion ip del servidor> <puerto servidor>
